<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfo513p\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfo513p/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRfo513p.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRfo513p\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRfo513p\appProdProjectContainer(array(
    'container.build_hash' => 'Rfo513p',
    'container.build_id' => '03531ee2',
    'container.build_time' => 1542013711,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfo513p');
